name: akkooo_todo
description: "Tasks are now managed beautifully and efficiently."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4
  flutter_native_splash: ^2.4.1
  pretty_bloc_observer: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  auto_route_generator: ^9.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  isar_generator: ^3.1.0+1


dependency_overrides:
  analyzer: ^6.4.1


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-Italic.ttf
          style: italic